// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-V1TjirHkHinwPXD4n-re_KoNpMTBv_g',
    appId: '1:355084646536:web:3291d6cc1747b8e422873d',
    messagingSenderId: '355084646536',
    projectId: 'travel-india-c3a8c',
    authDomain: 'travel-india-c3a8c.firebaseapp.com',
    storageBucket: 'travel-india-c3a8c.firebasestorage.app',
    measurementId: 'G-S18Y09R8M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYGyPPPmknqdClv8IPfgD0W4L-gMFRsOI',
    appId: '1:355084646536:android:e9e9f5ab8861d1d322873d',
    messagingSenderId: '355084646536',
    projectId: 'travel-india-c3a8c',
    storageBucket: 'travel-india-c3a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7AlKaL6LLrxSUgA4UWftjFXMdGIS1AG4',
    appId: '1:355084646536:ios:742926115259640622873d',
    messagingSenderId: '355084646536',
    projectId: 'travel-india-c3a8c',
    storageBucket: 'travel-india-c3a8c.firebasestorage.app',
    iosBundleId: 'com.example.travelIndia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7AlKaL6LLrxSUgA4UWftjFXMdGIS1AG4',
    appId: '1:355084646536:ios:742926115259640622873d',
    messagingSenderId: '355084646536',
    projectId: 'travel-india-c3a8c',
    storageBucket: 'travel-india-c3a8c.firebasestorage.app',
    iosBundleId: 'com.example.travelIndia',
  );
}
